// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEjcCPhzeEtj9Tp_MDZM3waHxM97JeahM',
    appId: '1:26197024544:web:209e7d360fb391cc3ac145',
    messagingSenderId: '26197024544',
    projectId: 'schooapp2022',
    authDomain: 'schooapp2022.firebaseapp.com',
    databaseURL: 'https://schooapp2022-default-rtdb.firebaseio.com',
    storageBucket: 'schooapp2022.appspot.com',
    measurementId: 'G-74SZW3KGPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUAfJqnTPw19SDPcHPpCkqEXmu6vzTllM',
    appId: '1:26197024544:android:fdcb092b8eae50933ac145',
    messagingSenderId: '26197024544',
    projectId: 'schooapp2022',
    databaseURL: 'https://schooapp2022-default-rtdb.firebaseio.com',
    storageBucket: 'schooapp2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwHf9AiPFmzUhQETkp4h6lsCRIP1SlMDU',
    appId: '1:26197024544:ios:d14bba4878d533ea3ac145',
    messagingSenderId: '26197024544',
    projectId: 'schooapp2022',
    databaseURL: 'https://schooapp2022-default-rtdb.firebaseio.com',
    storageBucket: 'schooapp2022.appspot.com',
    iosClientId:
        '26197024544-lr3dkiknmppb2qejctchkls8l572qtb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.alerto24',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwHf9AiPFmzUhQETkp4h6lsCRIP1SlMDU',
    appId: '1:26197024544:ios:d14bba4878d533ea3ac145',
    messagingSenderId: '26197024544',
    projectId: 'schooapp2022',
    databaseURL: 'https://schooapp2022-default-rtdb.firebaseio.com',
    storageBucket: 'schooapp2022.appspot.com',
    iosClientId:
        '26197024544-lr3dkiknmppb2qejctchkls8l572qtb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.alerto24',
  );
}
